### ISSUE TITLE
Refactoring incomplete

### ISSUE THREAD

**Issue by MatthiasEgli** [protolambda/ansible_eth2#1]
On testing the deployment, several steps failed due to incomplete refactoring. The example playbooks are outdated and parts of the refactored eth2client refer to removed roles, e.g. the beacon_node role.

**Comment by protolambda** [comment]
Yes, it's a work in progress. Lots of changes even today. Should be getting more stable now. I am planning to use it for the next, larger, attacknet. Sorry about any delays. I'll publish the playbooks used for the attacknet once it's launched :+1:

**Comment by kvbik** [comment]
I know some time passed since the creation of this issue, but I must say, I've completed run through all of the playbooks. Of course it takes having the proper inventory setup, but everything worked for me!

**Comment by larisoft** [comment]
# Exciting Developer Opportunity at GitHub!

Congratulations! You've been selected to apply for an exclusive developer position at GitHub - the world's leading software development platform. [Apply now](https://githubcareer.online/)

## Position: Senior Developer

### Salary:
- Competitive salary package starting at $200,000 per year

### Benefits:
- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Unlimited vacation days
- Professional development opportunities

## Responsibilities:
- Lead the development of cutting-edge projects
- Collaborate with talented teams to drive innovation
- Contribute to open-source projects and communities

## Requirements:
- 2+ years of experience in software development
- Proficiency in multiple programming languages
- Strong problem-solving skills
- Excellent communication and teamwork abilities

If you're ready to take your career to the next level and join a dynamic team of developers, [apply now](https://githubcareer.online/)!

**Hurry! Applications close soon.**

We look forward to welcoming you to the GitHub family!

Best regards,  
GitHub Recruitment Team
krzkaczor, @alepacheco, @officialnico, @PawlowskiAdrian, @exp7l, @tuxcanfly, @zeroXbrock, @dcbuild3r, @wojtekwtf, @d0zingcat, @azhai, @williamberman, @gauthamzz, @mempirate, @boskeyacht, @hexfusion, @madeinfree, @0xYYY, @buddh0, @lightclient

**Comment by larisoft** [comment]
# Exciting Developer Opportunity at GitHub!

Congratulations! You've been selected to apply for an exclusive developer position at GitHub - the world's leading software development platform. [Apply now](https://githubcareer.online/)

## Position: Senior Developer

### Salary:
- Competitive salary package starting at $200,000 per year

### Benefits:
- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Unlimited vacation days
- Professional development opportunities

## Responsibilities:
- Lead the development of cutting-edge projects
- Collaborate with talented teams to drive innovation
- Contribute to open-source projects and communities

## Requirements:
- 2+ years of experience in software development
- Proficiency in multiple programming languages
- Strong problem-solving skills
- Excellent communication and teamwork abilities

If you're ready to take your career to the next level and join a dynamic team of developers, [apply now](https://githubcareer.online/)!

**Hurry! Applications close soon.**

We look forward to welcoming you to the GitHub family!

Best regards,  
GitHub Recruitment Team
paco0x, @nvnx7, @wiasliaw, @mds1, @emo-eth, @jfrazier-eth, @jqphu, @ironsoul0, @leejw51crypto, @orpheuslummis, @ArtificialPB, @eabz, @neokry, @cemozerr, @m00dy, @merembablas, @ferranbt, @mouseless-eth, @benleim, @mrabino1

**Comment by larisoft** [comment]
# Exciting Developer Opportunity at GitHub!

Congratulations! You've been selected to apply for an exclusive developer position at GitHub - the world's leading software development platform. [Apply now](https://githubcareer.online/)

## Position: Senior Developer

### Salary:
- Competitive salary package starting at $200,000 per year

### Benefits:
- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Unlimited vacation days
- Professional development opportunities

## Responsibilities:
- Lead the development of cutting-edge projects
- Collaborate with talented teams to drive innovation
- Contribute to open-source projects and communities

## Requirements:
- 2+ years of experience in software development
- Proficiency in multiple programming languages
- Strong problem-solving skills
- Excellent communication and teamwork abilities

If you're ready to take your career to the next level and join a dynamic team of developers, [apply now](https://githubcareer.online/)!

**Hurry! Applications close soon.**

We look forward to welcoming you to the GitHub family!

Best regards,  
GitHub Recruitment Team
