### ISSUE TITLE
Is there a reason for the playbooks/roles symlink?

### ISSUE THREAD

**Issue by kvbik** [protolambda/ansible_eth2#3]
I wonder if it is necessary. I'd vote for having proper `ansible.cfg` path setup and removing the symlink.

**Comment by protolambda** [comment]
It's something I thought would be handy, as the playbooks directory is more commonly the root dir, and ansible can find the roles by default when in such root dir. In the testnet inventories we don't actually use it. I'm ok with removing it, if you prefer that.

**Comment by kvbik** [comment]
Hah, maybe just a result of me grep-ing through the code base all the time. I vote for removing. But I am not strong opinionated here.

**Comment by protolambda** [comment]
Cleaning up some ansible things, removed the symlink
